import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import localFont from "next/font/local";
import "./globals.css";
import { AppSidebar, AppSidebarTrigger } from "@/components/sidebar";
import OccurrencesProvider from "@/context/OccurrencesContext";
import { MOCK_OCCURRENCES_RESPONSE } from "@/mocks/occurrences";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`text-zinc-800 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <OccurrencesProvider initialOccurrences={MOCK_OCCURRENCES_RESPONSE}>
          <SidebarProvider>
            <AppSidebar />
            <AppSidebarTrigger />
            {children}
          </SidebarProvider>
        </OccurrencesProvider>
      </body>
    </html>
  );
}
